version: '3'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - MONGODB_URI=${MONGO_URI}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: